crud_paciente/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include ('paciente.urls', namespace = 'paciente')),
]

paciente/urls.py
from django.conf.urls import url
from paciente.views import PacienteList, PacienteCreate, PacienteUpdate, PacienteDelete

urlpatterns = [
	url(r'^$', PacienteList.as_view(), name='paciente_listar'),
    url(r'^listar$', PacienteList.as_view(), name='paciente_listar'),
    url(r'^nuevo$', PacienteCreate.as_view(), name='paciente_crear'),
    url(r'^editar/(?P<pk>\d+)$', PacienteUpdate.as_view(), name='paciente_editar'),
    url(r'^eliminar/(?P<pk>\d+)$', PacienteDelete.as_view(), name='paciente_eliminar'),
]

paciente/models.py
from django.db import models

# Create your models here.
class Paciente(models.Model):
	DOCUMENT_CHOICES = (('DNI','DNI'),
					('PASAPORTE','Pasaporte'),
					('CARNET','Carnet'),
					('RUC','Ruc'),
					)
	tipo_documento = models.CharField(
		max_length=10,
		choices = DOCUMENT_CHOICES,
		default='DNI',
		)
	numero_documento = models.CharField(max_length=50)
	nombres = models.CharField(max_length=50)
	apellido_paterno = models.CharField(max_length=50)
	apellido_materno = models.CharField(max_length=50)
	GENERO_CHOICES = (
    		('MASCULINO','Masculino'),
    		('FEMENINO','Femenino')
    	)
	genero = models.CharField(max_length=10, choices = GENERO_CHOICES)
	fecha_nacimiento = models.DateField()
	regalo_preferido = models.CharField(max_length=30)
	edad = models.IntegerField()

	def __str__(self):
	    return '{} {} {}'.format(self.nombres, self.apellido_paterno, self.apellido_materno)

paciente/forms.py
from django import forms
from paciente.models import Paciente

class PacienteForm(forms.ModelForm):
	class Meta:
		model = Paciente

		fields = [
			'tipo_documento',
			'numero_documento',
			'nombres',
			'apellido_paterno',
			'apellido_materno',
			'genero',
			'fecha_nacimiento',
			'regalo_preferido',
			'edad',
		]

		labels = {
			'tipo_documento' : 'Tipo de Documento',
			'numero_documento' : 'Numero de Documento',
			'nombres' : 'Nombres',
			'apellido_paterno' : 'Apellido Paterno',
			'apellido_materno' : 'Apellido Materno' ,
			'genero' : 'Genero',
			'fecha_nacimiento' : 'Fecha de Nacimiento',
			'regalo_preferido' : 'Regalo Preferido',
			'edad':'Edad',
		}

		widgets = {
			'tipo_documento' : forms.Select(attrs = {'class' : 'form-control'}),
			'numero_documento' : forms.TextInput(attrs = {'class' : 'form-control'}),
			'nombres' : forms.TextInput(attrs = {'class' : 'form-control'}),
			'apellido_paterno' : forms.TextInput(attrs = {'class' : 'form-control'}),
			'apellido_materno' : forms.TextInput(attrs = {'class' : 'form-control','id':'apellido_materno'}),
			'genero' : forms.Select(attrs = {'class' : 'form-control','id':'combo_genero'}),
			'fecha_nacimiento' : forms.TextInput(attrs = {'type':'date','class' : 'form-control', 'id':'fecha_nacimiento'}),
			'regalo_preferido': forms.Select(attrs = {'class' : 'form-control', 'id':'combo_regalo','readonly':'readonly'}),
			'edad': forms.TextInput(attrs = {'class':'form-control', 'id':'edad','readonly':'readonly'}),
		}

paciente/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from paciente.models import Paciente
from paciente.forms import PacienteForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

# Create your views here.
class PacienteList(ListView):
	model = Paciente
	template_name = 'persona_list.html'
	ordering = 'id'

class PacienteCreate(CreateView):
	model = Paciente
	form_class = PacienteForm
	template_name = 'paciente/paciente_form.html'
	success_url	= reverse_lazy('paciente:paciente_listar')

class PacienteUpdate(UpdateView):
	model = Paciente
	form_class = PacienteForm
	template_name = 'paciente/paciente_form.html'
	success_url	= reverse_lazy('paciente:paciente_listar')

class PacienteDelete(DeleteView):
	model = Paciente
	template_name = 'paciente/paciente_delete.html'
	success_url = reverse_lazy('paciente:paciente_listar')

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block tittle%} Document Base {% endblock %}</title>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
  </head>
  <body>

<div class="container">
{% block header %}
  <h1>Cabecera del cuerpo</h1>
{% endblock %}

{% block content %}
  <h1>Contenido del Cuerpo</h1>
{% endblock %}


{% block footer %}
<script type="text/javascript" src="{% static 'js/valida.js' %}"></script>
{% endblock %}
</div>
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  </body>
</html>

templates/paciente/paciente_delete.html
{% extends 'base/base.html' %}

{% block tittle%} Eliminar Pacientes {% endblock %}

{% block navbar %}
{% endblock %}

{% block header %}
  <h1>Confirmacion para Eliminar</h1>  
{% endblock %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <h3>Desea eliminar al paciente {{ paciente.nombres }} {{ paciente.apellido_paterno }} {{ paciente.apellido_materno }}?</h3>
  <button type="submit" class="btn btn-danger">
      Si, Eliminar
  </button> 
 <a class="btn btn-success" href="{% url 'paciente:paciente_listar' %}">Cancelar</a> 
</form>
{% endblock %}


{% block footer %}
  <h1></h1>  
{% endblock %}

templates/paciente/paciente_form.html
{% extends 'base/base.html' %}

{% block tittle%} Lista de Pacientes {% endblock %}

{% block navbar %}
{% endblock %}

{% block header %}
  <h1>Formulario de Pacientes</h1>
{% endblock %}

{% block content %}
  <form method="POST" id='my_form'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">
        Guardar
    </button>

  </form>
{% endblock %}

templates/paciente/paciente_list.html
{% extends 'base/base.html' %}

{% block tittle%} Lista de Pacientes {% endblock %}

{% block navbar %}
{% endblock %}

{% block header %}
<div class="row">
  <div class="col-8">
    <h1>Lista de Pacientes</h1>
  </div>
  <div class="col-4">
    <a class="btn btn-success" href="{% url 'paciente:paciente_crear' %}">Agregar Nuevo Paciente</a>
  </div>
</div>
  
{% endblock %}

{% block content %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Tipo de Documento</th>
        <th>Numero de Documento</th>
        <th>Nombre Completo</th>
        <th>Genero</th>
        <th>Fecha de Nacimiento</th>
        <th>Regalo Preferido</th>
        <th>Edad</th>
        <th colspan="4" style="text-align: center">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for paciente in object_list %}
      <tr>
        <td>{{ paciente.id }}</td>
        <td>{{ paciente.tipo_documento }}</td>
        <td>{{ paciente.numero_documento }}</td>
        <td>{{ paciente.nombres }} {{ paciente.apellido_paterno }} {{ paciente.apellido_materno }}</td>
        <td>{{ paciente.genero }}</td>
        <td>{{ paciente.fecha_nacimiento }}</td>
        <td>{{ paciente.regalo_preferido }}</td>
        <td>{{ paciente.edad }}</td>
        <td><a class="btn btn-primary" href="{% url 'paciente:paciente_editar' paciente.id %}">Editar</a></td>
        <td><a class="btn btn-danger" href="{% url 'paciente:paciente_eliminar' paciente.id %}">Eliminar</a></td>
      </tr>
      {% endfor %}

      {%else%}
      <h1>No hay registro de pacientes</h1>
      {%endif%}
    </tbody>

  </table>
{% endblock %}


{% block footer %}

{% endblock %}